AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for Cloud2 Cost and Usage Reporting"

Parameters:

  OperationsAccountId:
    Type: String
    Description: AWS Account ID of the customers account in Cloud2 Operations Setup
    Default: ""

  ExternalId:
    Type: String
    Description: External ID for cross-account role assumption
    Default: ""


Resources:
  ReportDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "cloud2-report-data-${AWS::AccountId}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReportDataBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AWSCostAndUsageReport
            Effect: Allow
            Principal:
              Service: 
                - billingreports.amazonaws.com
                - bcm-data-exports.amazonaws.com
            Action:
              - s3:GetBucketAcl
              - s3:GetBucketPolicy
              - s3:PutObject
            Resource:
              - !GetAtt ReportDataBucket.Arn
              - !Sub "${ReportDataBucket.Arn}/*"
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !GetAtt ReportDataBucket.Arn
              - !Sub "${ReportDataBucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: AllowBucketAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${OperationsAccountId}:root
            Action:
              - s3:GetBucketLocation
              - s3:ListBucket
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:GetObjectVersion
              - s3:GetObjectVersionAcl
            Resource: !GetAtt ReportDataBucket.Arn

          - Sid: AllowOperationsAccountRead
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${OperationsAccountId}:root
            Action:
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:GetObjectVersion
              - s3:GetObjectVersionAcl
            Resource:
              - !GetAtt ReportDataBucket.Arn
              - !Sub "${ReportDataBucket.Arn}/*"

  EventBridgeToEventBusRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloud2-eventbridge-to-eventbus-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowEventBridgeToPutEvents
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: events:PutEvents
                Resource: !Sub arn:aws:events:eu-west-1:${OperationsAccountId}:event-bus/cloud2-customer-events


  S3EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: cloud2-report-data-s3-event
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - "Object Created"
        detail:
          bucket:
            name:
              - !Ref ReportDataBucket
      State: ENABLED
      Targets:
        - Arn: !Sub arn:aws:events:eu-west-1:${OperationsAccountId}:event-bus/cloud2-customer-events
          Id: "cloud2-report-data-s3-event"
          RoleArn: !GetAtt EventBridgeToEventBusRole.Arn

  ReportingRolePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: cloud2-reporting-read-only-policy
      Description: Read-only access to specific S3 bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:HeadObject
              - s3:GetObjectAcl
              - s3:GetObjectVersion
              - s3:GetObjectVersionAcl
            Resource:
              - !GetAtt ReportDataBucket.Arn
              - !Sub "${ReportDataBucket.Arn}/*"


  BillingManagementPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: "cloud2-billing-management-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ce:*"
              - "bcm-data-exports:*"
            Resource: "*"

  ReportingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloud2-reporting-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !Sub arn:aws:iam::${OperationsAccountId}:root
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/job-function/Billing
        - arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess
        - !Ref BillingManagementPolicy
      Policies:
        - PolicyName: DescribeSelfRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetRole
                Resource: !Sub arn:aws:iam::${AWS::AccountId}:role/cloud2-reporting-role

  BCMDataExport:
    Type: AWS::BCMDataExports::Export
    DependsOn: BucketPolicy
    Properties:
      Export:
        Name: "cloud2-usage-export"
        Description: "Export of billing data"
        DataQuery:
          QueryStatement: "SELECT bill_bill_type, bill_billing_entity, bill_billing_period_end_date, bill_billing_period_start_date, bill_invoice_id, bill_invoicing_entity, bill_payer_account_id, bill_payer_account_name, cost_category, discount, discount_bundled_discount, discount_total_discount, identity_line_item_id, identity_time_interval, line_item_availability_zone, line_item_blended_cost, line_item_blended_rate, line_item_currency_code, line_item_legal_entity, line_item_line_item_description, line_item_line_item_type, line_item_net_unblended_cost, line_item_net_unblended_rate, line_item_normalization_factor, line_item_normalized_usage_amount, line_item_operation, line_item_product_code, line_item_tax_type, line_item_unblended_cost, line_item_unblended_rate, line_item_usage_account_id, line_item_usage_account_name, line_item_usage_amount, line_item_usage_end_date, line_item_usage_start_date, line_item_usage_type, pricing_currency, pricing_lease_contract_length, pricing_offering_class, pricing_public_on_demand_cost, pricing_public_on_demand_rate, pricing_purchase_option, pricing_rate_code, pricing_rate_id, pricing_term, pricing_unit, product, product_comment, product_fee_code, product_fee_description, product_from_location, product_from_location_type, product_from_region_code, product_instance_family, product_instance_type, product_instancesku, product_location, product_location_type, product_operation, product_pricing_unit, product_product_family, product_region_code, product_servicecode, product_sku, product_to_location, product_to_location_type, product_to_region_code, product_usagetype, reservation_amortized_upfront_cost_for_usage, reservation_amortized_upfront_fee_for_billing_period, reservation_availability_zone, reservation_effective_cost, reservation_end_time, reservation_modification_status, reservation_net_amortized_upfront_cost_for_usage, reservation_net_amortized_upfront_fee_for_billing_period, reservation_net_effective_cost, reservation_net_recurring_fee_for_usage, reservation_net_unused_amortized_upfront_fee_for_billing_period, reservation_net_unused_recurring_fee, reservation_net_upfront_value, reservation_normalized_units_per_reservation, reservation_number_of_reservations, reservation_recurring_fee_for_usage, reservation_reservation_a_r_n, reservation_start_time, reservation_subscription_id, reservation_total_reserved_normalized_units, reservation_total_reserved_units, reservation_units_per_reservation, reservation_unused_amortized_upfront_fee_for_billing_period, reservation_unused_normalized_unit_quantity, reservation_unused_quantity, reservation_unused_recurring_fee, reservation_upfront_value, resource_tags, savings_plan_amortized_upfront_commitment_for_billing_period, savings_plan_end_time, savings_plan_instance_type_family, savings_plan_net_amortized_upfront_commitment_for_billing_period, savings_plan_net_recurring_commitment_for_billing_period, savings_plan_net_savings_plan_effective_cost, savings_plan_offering_type, savings_plan_payment_option, savings_plan_purchase_term, savings_plan_recurring_commitment_for_billing_period, savings_plan_region, savings_plan_savings_plan_a_r_n, savings_plan_savings_plan_effective_cost, savings_plan_savings_plan_rate, savings_plan_start_time, savings_plan_total_commitment_to_date, savings_plan_used_commitment FROM COST_AND_USAGE_REPORT"
          TableConfigurations:
            COST_AND_USAGE_REPORT:
              INCLUDE_MANUAL_DISCOUNT_COMPATIBILITY: "FALSE"
              INCLUDE_RESOURCES: "TRUE"
              INCLUDE_SPLIT_COST_ALLOCATION_DATA: "TRUE"
              TIME_GRANULARITY: "HOURLY"
        DestinationConfigurations:
          S3Destination:
            S3Bucket: !Ref ReportDataBucket
            S3Prefix: "usage/cur"
            S3Region: "us-east-1"
            S3OutputConfigurations:
              Compression: "PARQUET"
              Format: "PARQUET"
              OutputType: "CUSTOM"
              Overwrite: "OVERWRITE_REPORT"
        RefreshCadence:
          Frequency: "SYNCHRONOUS"

  BCMDataExportFocus:
    Type: AWS::BCMDataExports::Export
    DependsOn: BucketPolicy
    Properties:
      Export:
        Name: "cloud2-usage-export-focus"
        Description: "Export of billing data using FOCUS_1_0_AWS configuration"
        DataQuery:
          QueryStatement: "SELECT AvailabilityZone, BilledCost, BillingAccountId, BillingAccountName, BillingCurrency, BillingPeriodEnd, BillingPeriodStart, ChargeCategory, ChargeClass, ChargeDescription, ChargeFrequency, ChargePeriodEnd, ChargePeriodStart, CommitmentDiscountCategory, CommitmentDiscountId, CommitmentDiscountName, CommitmentDiscountStatus, CommitmentDiscountType, ConsumedQuantity, ConsumedUnit, ContractedCost, ContractedUnitPrice, EffectiveCost, InvoiceIssuerName, ListCost, ListUnitPrice, PricingCategory, PricingQuantity, PricingUnit, ProviderName, PublisherName, RegionId, RegionName, ResourceId, ResourceName, ResourceType, ServiceCategory, ServiceName, SkuId, SkuPriceId, SubAccountId, SubAccountName, Tags, x_CostCategories, x_Discounts, x_Operation, x_ServiceCode, x_UsageType FROM FOCUS_1_0_AWS"
          TableConfigurations:
            FOCUS_1_0_AWS: {}
        DestinationConfigurations:
          S3Destination:
            S3Bucket: !Ref ReportDataBucket
            S3Prefix: "usage/focus"
            S3Region: "us-east-1"
            S3OutputConfigurations:
              Compression: "PARQUET"
              Format: "PARQUET"
              OutputType: "CUSTOM"
              Overwrite: "OVERWRITE_REPORT"
        RefreshCadence:
          Frequency: "SYNCHRONOUS"

  HealthEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: cloud2-aws-health
      Description: Rule to forward Health events to the operations account
      EventPattern:
        source:
          - aws.health
        detail-type:
          - AWS Health Event
      Targets:
        - Arn: !Sub arn:aws:events:eu-west-1:${OperationsAccountId}:event-bus/cloud2-customer-events
          Id: cloud2-aws-health-target
          RoleArn: !GetAtt EventBridgeToEventBusRole.Arn

Outputs:
  ReportingRoleArn:
    Description: ARN of the reporting role
    Value: !GetAtt ReportingRole.Arn
