AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  
  InitializeConfigVersion:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: "Set to 'true' only during the first deployment to initialize the configuration version."

  OperationsAccountId:
    Type: String
    Description: The AWS account ID of the operations account

  EventBusName:
    Type: String
    Description: The name of the event bus

Conditions:
  CreateInitialConfigVersion: !Equals [!Ref InitializeConfigVersion, "true"]

Resources:

  AppConfigApp:
    Type: AWS::AppConfig::Application
    Properties:
      Name: cloud2
      Description: Cloud2 Configuration Management

  AppConfigEnvironment:
    Type: AWS::AppConfig::Environment
    Properties:
      ApplicationId: !Ref AppConfigApp
      Name: cloud2
      Description: Cloud2 Configuration Management

  AppConfigDeploymentStrategy:
    Type: AWS::AppConfig::DeploymentStrategy
    Properties:      
      Description: Cloud2 Configuration Management
      DeploymentDurationInMinutes: 0
      FinalBakeTimeInMinutes: 0
      GrowthFactor: 100
      GrowthType: EXPONENTIAL
      Name: cloud2-deployment-strategy
      ReplicateTo: NONE

  AppConfigConfigProfile:
    Type: AWS::AppConfig::ConfigurationProfile    
    Properties:
      ApplicationId: !Ref AppConfigApp
      LocationUri: hosted
      Name: cloud2-configuration
      Validators:
        - Content: |
            {
              "hello": "AppConfig Configuration for Cloud2 Provisioning",
              "description": "Configuration JSON for AppConfig",
              "type": "object",
              "properties": {               
                "operations_account_id": {
                  "description": "The AWS account ID of the operations account",
                  "type": "string"
                },
                "operations_sink_identifier": {
                  "description": "The identifier for the operations sink",
                  "type": "string"
                },
                "operations_event_bus_name": {
                  "description": "The name of the operations event bus",
                  "type": "string"
                },
                "external_id": {
                  "description": "The external ID for cross-account access",
                  "type": "string"
                },
                "main_region": {
                  "description": "The main AWS region for operations",
                  "type": "string"
                },
                "regions": {
                  "description": "List of supported AWS regions",
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "required": [ 
                "operations_account_id",
                "operations_sink_identifier",
                "operations_event_bus_name",
                "external_id",
                "main_region",
                "regions"
              ]
            }
          Type: JSON_SCHEMA

  AppConfigConfigVersion:
    Type: AWS::AppConfig::HostedConfigurationVersion
    Condition: CreateInitialConfigVersion  # Only create on first deployment    
    Properties:
      ApplicationId: !Ref AppConfigApp
      ConfigurationProfileId: !Ref AppConfigConfigProfile
      ContentType: application/json
      Content: |
        {
          "operations_account_id": "",
          "operations_sink_identifier": "",
          "operations_event_bus_name": "",
          "external_id": "",
          "main_region": "",
          "portfolios": [{
            "id": "Cloud2 Portfolio",
            "products": [{
              "id": "Cloud2 Product",
              "provisioning_artifact_id": "Cloud2 Product Provisioning Artifact",
              "parameters": {
                
            }]
          }]
        }

  AppConfigDeployment:
    Type: AWS::AppConfig::Deployment
    Condition: CreateInitialConfigVersion  # Only create on first deployment    
    Properties:
      ApplicationId: !Ref AppConfigApp
      ConfigurationProfileId: !Ref AppConfigConfigProfile
      ConfigurationVersion: !Ref AppConfigConfigVersion
      DeploymentStrategyId: !Ref AppConfigDeploymentStrategy
      EnvironmentId: !Ref AppConfigEnvironment

  AppConfigExtensionAssociation:
    Type: AWS::AppConfig::ExtensionAssociation
    Properties:
      ExtensionIdentifier: "AWS.AppConfig.DeploymentNotificationsToEventBridge"
      ExtensionVersionNumber: 1
      ResourceIdentifier: !Sub "arn:aws:appconfig:${AWS::Region}:${AWS::AccountId}:application/${AppConfigApp}/configurationprofile/${AppConfigConfigProfile}"