AWSTemplateFormatVersion: '2010-09-09'
Description: Stack to create a consolidated cloud2-spotter role with combined permissions from config, management, and security roles.

Parameters:
  ExternalId:
    Type: String
    Description: The external ID provided by Spotter for secure role assumption.

  SpotterAccountId:
    Type: String
    Description: The AWS account ID for Spotter to assume the role.

Resources:
  SpotterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: cloud2-spotter
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${SpotterAccountId}:root"
            Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                sts:ExternalId:
                  Ref: ExternalId
      Policies:
        - PolicyName: cloud2-spotter-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ce:GetCostForecast
                  - ce:GetCostAndUsage
                  - ce:GetReservationPurchaseRecommendation
                  - ce:GetRightsizingRecommendation
                  - ce:GetSavingsPlansPurchaseRecommendation
                  - ce:GetTags
                  - ce:ListCostAllocationTags
                Resource: "*"
              - Effect: Allow
                Action:
                  - organizations:ListAccounts
                Resource: "*"
              - Effect: Allow
                Action:
                  - securityhub:GetFindings
                Resource: "*"
              - Effect: Allow
                Action:
                  - config:ListAggregateDiscoveredResources
                  - iam:ListAccountAliases
                  - support:DescribeTrustedAdvisorChecks
                  - support:DescribeTrustedAdvisorCheckSummaries
                Resource: "*" 