AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  OperationsAccountId:
    Type: String
    Description: The AWS account ID of the operations account

Resources:
  CallHomeSimulatorDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Automation
      DocumentFormat: YAML
      Name: cloud2-call-home-simulator
      UpdateMethod: NewVersion
      Content:
        schemaVersion: "0.3"
        description: Automation for placing a call-home event onto EventBridge
        mainSteps:
          - name: SendEventBridgeEvent
            action: aws:executeAwsApi
            inputs:
              Service: events
              Api: PutEvents
              Entries:
                - Source: cloud2.callhome.simulator
                  DetailType: CallHomeSimulation
                  Detail: '{"status":"success","origin":"automation", "cause": "test"}'
                  EventBusName: !Sub "arn:aws:events:${AWS::Region}:${OperationsAccountId}:event-bus/cloud2-customer-events"

          - name: SendSNSEvent
            action: aws:executeAwsApi
            inputs:
              Service: sns
              Api: Publish
              TopicArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:cloud2-events"
              Message: '{"status":"success","origin":"automation", "cause": "test"}'

          - name: SendCloudWatchMetric
            action: aws:executeAwsApi
            inputs:
              Service: cloudwatch
              Api: PutMetricData
              Namespace: Cloud2/Events
              MetricData:
                - MetricName: Test
                  Value: 1