name: monitoring-baseline

env:
  HOME_REGION: eu-central-1
  ACTIVE_REGIONS: eu-central-1,eu-west-1,us-east-1

  SERVICE_ACCOUNT_ID: ${{ vars.SERVICE_ACCOUNT_ID }}
  SAM_CLI_TELEMETRY: 0
  VERSION: 1.2.${{ github.run_number }}

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'services/monitoring-baseline/**'
      - 'scripts/**'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Service Catalog
        uses: ./.github/actions/service-catalog-build
        with:
          service-directory: monitoring-baseline

  dev-publish:
    runs-on: ubuntu-latest
    environment: dev
    needs:
      - build
    steps:
      - name: Setup
        uses: ./.github/actions/service-catalog-setup
        with:
          service-directory: monitoring-baseline

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.SERVICE_ACCOUNT_ID }}:role/cloud2-github-oicd
          role-session-name: GitHubActions
          aws-region: ${{ env.HOME_REGION }}

      - name: Publish Dev Portfolios
        working-directory: services/monitoring-baseline/artifacts
        env:
          VERSION: ${{ env.VERSION }}
          SERVICE_ACCOUNT_ID: ${{ env.SERVICE_ACCOUNT_ID }}
          ACTIVE_REGIONS: ${{ env.ACTIVE_REGIONS }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ../../../scripts/publish.sh dev

  dev-release:
    runs-on: ubuntu-latest
    environment: dev
    needs:
      - dev-publish
    steps:
      - name: Setup
        uses: ./.github/actions/service-catalog-setup
        with:
          service-directory: monitoring-baseline

      - name: Deploy Service Catalog
        uses: ./.github/actions/service-catalog-release
        with:
          environment: dev
          version: ${{ env.VERSION }}
          service-account-id: ${{ env.SERVICE_ACCOUNT_ID }}
          active-regions: ${{ env.ACTIVE_REGIONS }}
          max-active-versions: 5
          home-region: ${{ env.HOME_REGION }}
          working-directory: services/monitoring-baseline/artifacts

  prod-publish:
    runs-on: ubuntu-latest
    environment: prod
    needs:
      - dev-release
    steps:
      - name: Setup
        uses: ./.github/actions/service-catalog-setup
        with:
          service-directory: monitoring-baseline

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.SERVICE_ACCOUNT_ID }}:role/cloud2-github-oicd
          role-session-name: GitHubActions
          aws-region: ${{ env.HOME_REGION }}

      - name: Publish Prod Portfolios
        working-directory: services/monitoring-baseline/artifacts
        env:
          VERSION: ${{ env.VERSION }}
          SERVICE_ACCOUNT_ID: ${{ env.SERVICE_ACCOUNT_ID }}
          ACTIVE_REGIONS: ${{ env.ACTIVE_REGIONS }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ../../../scripts/publish.sh prod

  prod-release:
    runs-on: ubuntu-latest
    environment: prod
    needs:
      - prod-publish
    steps:
      - name: Setup
        uses: ./.github/actions/service-catalog-setup
        with:
          service-directory: monitoring-baseline

      - name: Deploy Service Catalog
        uses: ./.github/actions/service-catalog-release
        with:
          environment: prod
          version: ${{ env.VERSION }}
          service-account-id: ${{ env.SERVICE_ACCOUNT_ID }}
          active-regions: ${{ env.ACTIVE_REGIONS }}
          max-active-versions: 5
          home-region: ${{ env.HOME_REGION }}
          working-directory: services/monitoring-baseline/artifacts