name: reporting-baseline

env:
  HOME_REGION: eu-central-1
  ACTIVE_REGIONS: eu-central-1,eu-west-1,us-east-1
  SERVICE_ACCOUNT_ID: ${{ vars.SERVICE_ACCOUNT_ID }}
  SAM_CLI_TELEMETRY: 0
  VERSION: 1.1.${{ github.run_number }}

permissions:
  id-token: write
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'services/reporting/**'
      - 'scripts/**'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Service Catalog
        uses: ./.github/actions/service-catalog-build
        with:
          service-directory: reporting

  dev-publish:
    runs-on: ubuntu-latest
    environment: dev
    needs:
      - build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: services/reporting/artifacts

      - name: Publish Dev Portfolios
        uses: ./.github/actions/service-catalog-publish
        with:
          environment: dev
          version: ${{ env.VERSION }}
          service-account-id: ${{ env.SERVICE_ACCOUNT_ID }}
          active-regions: ${{ env.ACTIVE_REGIONS }}
          home-region: ${{ env.HOME_REGION }}
          working-directory: services/reporting/artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}

  dev-release:
    runs-on: ubuntu-latest
    environment: dev
    needs:
      - dev-publish
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: services/reporting/artifacts

      - name: Deploy Service Catalog
        uses: ./.github/actions/service-catalog-release
        with:
          environment: dev
          version: ${{ env.VERSION }}
          service-account-id: ${{ env.SERVICE_ACCOUNT_ID }}
          active-regions: ${{ env.ACTIVE_REGIONS }}
          max-active-versions: 5
          home-region: ${{ env.HOME_REGION }}
          working-directory: services/reporting/artifacts

  prod-publish:
    runs-on: ubuntu-latest
    environment: prod
    needs:
      - dev-release
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: services/reporting/artifacts

      - name: Publish Prod Portfolios
        uses: ./.github/actions/service-catalog-publish
        with:
          environment: prod
          version: ${{ env.VERSION }}
          service-account-id: ${{ env.SERVICE_ACCOUNT_ID }}
          active-regions: ${{ env.ACTIVE_REGIONS }}
          home-region: ${{ env.HOME_REGION }}
          working-directory: services/reporting/artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}

  prod-release:
    runs-on: ubuntu-latest
    environment: prod
    needs:
      - prod-publish
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: services/reporting/artifacts

      - name: Deploy Service Catalog
        uses: ./.github/actions/service-catalog-release
        with:
          environment: prod
          version: ${{ env.VERSION }}
          service-account-id: ${{ env.SERVICE_ACCOUNT_ID }}
          active-regions: ${{ env.ACTIVE_REGIONS }}
          max-active-versions: 5
          home-region: ${{ env.HOME_REGION }}
          working-directory: services/reporting/artifacts